title: Formula Blob Dev Blog
description: Updates and insights from the development of Formula Blob.
baseurl: "/blog" # Adjust if hosted in a subdirectory
url: "https://formula-blob.geoffpetrie.com"
theme: minima