title: Formula Blob Dev Blog
description: Updates and insights from the development of Formula Blob.
baseurl: "/formula-blob/blog" # Adjust if hosted in a subdirectory
url: "https://geopet.github.io"
theme: minima