name: Lint Pico-8 Cart

on:
  push:
    paths:
      - '**.p8'
  pull_request:
    paths:
      - '**.p8'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Clone picotool
      run: |
        git clone https://github.com/dansanderson/picotool.git tools/picotool

    - name: Lint .p8 files
      run: |
<<<<<<< HEAD
        for file in $(find . -name "*.p8" -not -path "./tools/*"); do
=======
        for file in $(find . -name "*.p8" -not -path "./picotool/*"); do
>>>>>>> 62073de (fix(linting): exclude picotool directory)
          echo "Linting $file"
          python3 tools/picotool/picotool.py lint "$file"
        done